pipe:
	cc pipe.c

sigaction:
	cc sigaction.c

sigint_cat:
	cc sigint_cat.c && ./a.out

signalfd:
	cc signalfd.c

sigint_cat_select:
	cc sigint_cat_select.c && ./a.out

pipe_queue:
	cc -pthread pipe_queue.c

pipe_close_handling:
	cc pipe_close_handling.c

eventfd:
	man eventfd
